### ISSUE TITLE
Change icon for "ask the community"

### ISSUE THREAD

**Issue by Zimmi48** [coq/rocq-prover.org#21]
I don't know why this uses an animal foot icon. Perhaps, that's a camel's. In any case, this seems ill-suited for us. This could be replaced either by the Rocq logo (since this is the Rocq community), or by the Zulip logo (since this directs to Zulip).

![image](https://github.com/user-attachments/assets/860d64f7-a687-45f5-b9c0-ba147f563c66)

**Comment by TheoWinterhalter** [comment]
I think it's like three silhouettes to represent a group of people, not a paw print.

**Comment by Zimmi48** [comment]
Oh OK, never mind then!
